# GitLab CI/CD configuration for Vite React app deployment to GitLab Pages
# OPTIMIZED FOR SPEED 🚀

# Use smaller, faster Node.js image
image: node:18-alpine

# Single stage for faster deployment
stages:
  - deploy

# Aggressive caching for speed
cache:
  key: npm-cache
  paths:
    - app/node_modules/
    - app/.npm/

# Combined build and deploy for speed
pages:
  stage: deploy
  script:
    - cd app
    - echo "🚀 FAST DEPLOYMENT STARTING..."
    
    # Quick dependency install with cache
    - npm install --prefer-offline --no-audit --progress=false
    
    # Fast build
    - npm run build
    
    # Quick deploy
    - cd ..
    - mkdir public
    - cp -r app/dist/* public/
    - echo "✅ DEPLOYED! Site will be live in ~1 minute"
    
  artifacts:
    paths:
      - public
  only:
    - main
    - master


