# GitLab CI/CD configuration for React Vite app with proper asset handling
image: node:20-alpine

# Cache configuration
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/
  policy: pull-push

# Define stages
stages:
  - build
  - deploy

# Variables for optimization
variables:
  NODE_ENV: "production"
  CI: "true"

# Build stage
build:
  stage: build
  timeout: 30m
  before_script:
    - echo "Node version:" && node --version
    - echo "NPM version:" && npm --version
    - echo "Installing dependencies..."
  script:
    - npm ci --cache .npm --prefer-offline --no-audit --no-fund --silent
    - echo "Building application..."
    - npm run build
    - echo "Build completed successfully!"
    - ls -la dist/
    - echo "Checking for assets..."
    - ls -la dist/assets/ || echo "No assets directory found"
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .npm/
    policy: pull-push
  only:
    - main
    - master

# Deploy to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - echo "Preparing deployment..."
  script:
    - mkdir public
    - cp -r dist/* public/
    - echo "Files copied to public directory:"
    - ls -la public/
    - echo "Checking assets in public:"
    - ls -la public/assets/ || echo "No assets directory in public"
    - echo "Deployment ready!"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - build
  cache: {}
  only:
    - main
    - master
