# GitLab CI/CD configuration for React Vite app
image: node:18

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/

# Define stages
stages:
  - build
  - deploy

# Build stage
build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main
    - master

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - main
    - master
